//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Flight
    {
        public int ID { get; set; }
        public int StartBusStationID { get; set; }
        public int EndBusStationID { get; set; }
        public string DateTimeFrom { get; set; }
        public string DateTimeTo { get; set; }
        public string TravelLong { get; set; }
        public int FlightNum { get; set; }
        public string FlightName { get; set; }
        public int PlacesCount { get; set; }
        public decimal TicketCost { get; set; }
    }
}
