//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int ID { get; set; }
        public int OrderID { get; set; }
        public string UserName { get; set; }
        public string UserLname { get; set; }
        public int UserDocNum { get; set; }
        public int UserNum { get; set; }
        public string Status { get; set; }
    }
}
